$ErrorActionPreference = "Stop"

<#
SCRIPTS-RATIONALIZATION-2026-05-10:
This enhancement script remains active as the recursive non-regression pass.
For current guidance, read scripts/README.md, ci-cd-pipeline.md, linting-rules.md,
reference-verification.md, and prompt-metadata-validation.md before changing it.
Future destructive or broad file-changing revisions should preserve idempotency,
use literal paths, record build_log.md rows, and consider ShouldProcess-style dry-run behavior.
#>

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Workspace = Split-Path -Parent $Root
$LogPath = Join-Path $Root "build_log.md"
$InventoryPath = Join-Path $Root "docs/repository_source_inventory.md"
$Marker = "<!-- ENHANCEMENT-PASS-2026-05-05-NON-REGRESSION -->"

function Get-RelativePath {
    param([string]$Path)
    return $Path.Substring($Workspace.Length + 1).Replace("\", "/")
}

function Get-RepoFiles {
    Get-ChildItem -Path $Workspace -Recurse -Force -File | Where-Object {
        $_.FullName -notmatch '\\\.git\\' -and
        $_.FullName -notmatch '\\node_modules\\' -and
        $_.FullName -notmatch '\\dist\\' -and
        $_.FullName -notmatch '\\build\\'
    }
}

function Ensure-Log {
    if (-not (Test-Path $LogPath)) {
        Set-Content -Path $LogPath -Encoding UTF8 -Value "| Task ID | Description | Source Files Analyzed | Target Path | Status |`n|---|---|---|---|---|"
        return
    }
    $raw = Get-Content $LogPath -Raw
    if ($raw -notmatch '\| Task ID \| Description \| Source Files Analyzed \| Target Path \| Status \|') {
        $archive = $raw
        Set-Content -Path $LogPath -Encoding UTF8 -Value "| Task ID | Description | Source Files Analyzed | Target Path | Status |`n|---|---|---|---|---|`n`n## Archived Previous Log Format`n`n$archive"
    }
}

function Test-LoggedDone {
    param([string]$TaskId)
    if (-not (Test-Path $LogPath)) { return $false }
    $raw = Get-Content $LogPath -Raw
    return $raw -match "\|\s*$([regex]::Escape($TaskId))\s*\|[^\r\n]*\|\s*DONE\s*\|"
}

function Write-TaskLog {
    param([string]$TaskId, [string]$Description, [string]$Sources, [string]$TargetPath, [string]$Status)
    Add-Content -Path $LogPath -Encoding UTF8 -Value "| $TaskId | $Description | $Sources | $TargetPath | $Status |"
}

function Get-SourceSummary {
    param([string[]]$Paths)
    $highSignal = $Paths | Where-Object {
        $_ -match '^(AGENTS|AI_EXECUTION_PROMPTS|CLAUDE|LOCAL_EXECUTION_MODE|README)\.md$' -or
        $_ -match '^governance/' -or
        $_ -match '(^|/)continue/rules/' -or
        $_ -match '(^|/)cursor/rules/' -or
        $_ -match '(^|/)github/' -or
        $_ -match '^Source/(\.cursor|Changelogs|Codinglessonslearnt|own prompts|prompt-template|prompts/next-shadcn|prompts/react-19|prompts/tailwind-4|scripts)/'
    }
    return "Full repository scan captured in AI_PROMPTING_FOLDERSTRUCTURE/docs/repository_source_inventory.md; high-signal sources: " + (($highSignal | Sort-Object) -join "; ")
}

function New-InventoryContent {
    param([string[]]$Paths)
    $items = ($Paths | Sort-Object | ForEach-Object { "- $_" }) -join "`n"
@"
# Repository Source Inventory

$Marker

Generated by `scripts/enhance_product_engineering_os.ps1` during the recursive non-regression enhancement pass.

## Purpose
This inventory records the repository files scanned before enhancing the Product-Engineering OS. Future runs must refresh this inventory before changing templates, instructions, governance, scripts, or QA assets.

## Extracted High-Signal Source Classes
- Execution entrypoints: `AGENTS.md`, `AI_EXECUTION_PROMPTS.md`, `CLAUDE.md`, `LOCAL_EXECUTION_MODE.md`.
- Governance: `governance/controller.md`, `governance/agent_execution_rules.md`, `governance/execution_authority_and_automation_rules.md`, `governance/business_process_automation_prompts.md`, `governance/ui_ux_rules.md`, `governance/local_context.md`.
- Editor rules: `continue/rules/00-governance.md`, `cursor/rules/00-governance.mdc`, `Source/.cursor/rules/testrule.md`.
- Operational memory: `Source/Changelogs/*`, `Source/Codinglessonslearnt/*`.
- Prompt platform standards: `Source/prompt-template/*`, `Source/prompts/*/aiprompt.json`, framework rule files, and `Source/scripts/validate-structure.js`.
- Design and product standards: `AI_PROMPTING_FOLDERSTRUCTURE/UI Masterprompt.md`, `AI_PROMPTING_FOLDERSTRUCTURE/UX Masterprompt.md`, `Source/own prompts/design-master-rules.md`.

## Full File List
$items
"@
}

function New-EnhancementBlock {
    param([string]$Domain, [string]$Kind)
@"

$Marker

## Recursive Enhancement Pass - Non-Regression Layer

### Self-Challenge Result
Analyzing all repository sources for $Domain patterns revealed that the existing Product-Engineering OS was structurally strong but could be deepened with newly discovered governance, editor-rule, changelog, coding-lesson, and framework-specific standards. This section augments the existing file without deleting or reducing any prior content.

### Newly Integrated Repository Paradigms
- Execution authority: treat clear user requests as execution instructions. Do not create permission loops for non-destructive governance, changelog, documentation, GitHub/Jira-supporting, or delivery-supporting artifacts when those actions are naturally implied.
- Mandatory confirmation boundary: ask before destructive deletion, irreversible overwrite, production deployment, external publishing, external messaging, security-sensitive changes, or access-control-sensitive work.
- Canonical read order: read governance/controller, execution authority rules, coding lessons, UI/UX rules when UI is affected, changelogs, latest versioning artifacts, the global OS controller, SYSTEM.md, and the local target instructions.
- Append-only knowledge: changelogs, coding lessons, build logs, governance history, and design/system decisions must be augmented rather than replaced. Never overwrite delivery history to make a clean narrative.
- Cursor/Continue integration: when `.cursor`, `cursor/rules`, `.continue`, or `continue/rules` are present, treat them as editor-enforced local governance. Mirror their standards into scripts/linting-rules.md and QA checks before changing generated assets.
- Prompt package discipline: prompt collections must include validated metadata such as name, description, type, slug, files, author, development process, categories, tags, tech stack, model, editor, and version. Slugs must be unique, hidden prompt-package files are invalid, and prompt packages should avoid nested structures unless explicitly supported.
- Framework standards: Next 15 and React 19 work should prefer App Router, Server Components by default, Client Components only for interaction, strict TypeScript, explicit props, route-level loading/error boundaries, Suspense where appropriate, minimal dependencies, and shadcn/ui components installed with the current `npx shadcn@latest add` command.
- Design standards: preserve every working entrypoint, validate mobile and desktop layouts, prevent overflow and broken focus states, keep dropdowns readable, maintain usable CTAs/filters/dialogs/navigation, and make hierarchy follow business priority.
- Operational risk standards: compare at least two solution options when risk is non-trivial, choose the smallest regression-risk path, re-check previously working flows, update governance/changelog artifacts when naturally implied, and provide QA handoff.
- Changelog-derived lessons: use modular feature registries instead of single-purpose app shells, add SSRF/private-network guardrails for request tools, redact sensitive headers, cap timeouts, use `cache: no-store` when stale perception is harmful, and distinguish runtime-observed evidence from code-inferred evidence.
- Coding-lesson traps: align TypeScript interfaces with SQL columns, handle Supabase FK relation typing deliberately, prefer `getUser()` over trusting `getSession()` for auth-critical checks, avoid middleware redirect traps, avoid RLS policies that join across protected tables, validate provider-specific geospatial params, never mix bbox and point-radius casually, apply provider throttling/backoff, and avoid hard filters that zero out valid results.

### Required Enhancement Checklist
```json
{
  "repository_sources_analyzed": "all files listed in docs/repository_source_inventory.md",
  "non_regression": {
    "existing_content_preserved": true,
    "append_only_change": true,
    "working_features_rechecked": "required before handoff"
  },
  "execution_authority": {
    "execute_clear_requests": true,
    "ask_only_for_real_ambiguity_or_mandatory_confirmation": true,
    "update_related_governance_and_delivery_artifacts_when_implied": true
  },
  "interfaces": {
    "json_schema_required": true,
    "react_props_required_when_user_facing": true,
    "api_envelope_required_when_server_or_integration": true,
    "data_invariants_required_when_database": true
  },
  "qa": {
    "mobile_desktop_validation": true,
    "accessibility_focus_validation": true,
    "regression_matrix_required": true,
    "changelog_or_build_log_update_required": true
  }
}
```

### $Kind Application Rule
For this $Kind artifact, every future generated asset must explicitly state which newly discovered repository standards apply, which do not apply, and why. If a source class is absent in a future run, record that absence instead of silently assuming it does not matter.
"@
}

function Add-Enhancement {
    param([string]$TaskId, [string]$RelativePath, [string]$Description, [string]$Sources, [string]$Domain, [string]$Kind)
    $target = Join-Path $Root $RelativePath
    if (-not (Test-Path $target)) {
        Write-TaskLog $TaskId "$Description skipped because target is missing" $Sources $RelativePath "PENDING"
        return
    }
    $raw = Get-Content $target -Raw
    if ($raw -match [regex]::Escape($Marker)) {
        if (-not (Test-LoggedDone $TaskId)) {
            Write-TaskLog $TaskId "$Description already present" $Sources $RelativePath "DONE"
        }
        return
    }
    Add-Content -Path $target -Encoding UTF8 -Value (New-EnhancementBlock $Domain $Kind)
    Write-TaskLog $TaskId $Description $Sources $RelativePath "DONE"
}

Ensure-Log
$files = Get-RepoFiles
$paths = $files | ForEach-Object { Get-RelativePath $_.FullName }
$sources = Get-SourceSummary $paths

New-Item -ItemType Directory -Path (Split-Path -Parent $InventoryPath) -Force | Out-Null
if ((-not (Test-Path $InventoryPath)) -or ((Get-Content $InventoryPath -Raw) -notmatch [regex]::Escape($Marker))) {
    Set-Content -Path $InventoryPath -Encoding UTF8 -Value (New-InventoryContent $paths)
    Write-TaskLog "ENH-SCAN-001" "Scan full repository and write source inventory for recursive enhancement" $sources "docs/repository_source_inventory.md" "DONE"
} elseif (-not (Test-LoggedDone "ENH-SCAN-001")) {
    Write-TaskLog "ENH-SCAN-001" "Full repository source inventory already present" $sources "docs/repository_source_inventory.md" "DONE"
}

$targets = @(
    @("ENH-CORE-001","ai_dev_system.md","Enhance master controller with recursive non-regression governance","core","controller"),
    @("ENH-SYSTEM-001","SYSTEM.md","Enhance designer folderstructure controller with new source patterns","system","controller"),
    @("ENH-BE-INST-001","backend/ai_instructions.md","Enhance backend AI instructions","backend","instruction"),
    @("ENH-BE-TMPL-001","backend/prompt_template_backend_api.md","Enhance backend API prompt template","backend","template"),
    @("ENH-BE-TMPL-002","backend/service_layer_template.md","Enhance service layer template","backend","template"),
    @("ENH-BE-GUIDE-001","backend/error_handling.md","Enhance backend error handling guide","backend","guide"),
    @("ENH-DB-INST-001","database/ai_instructions.md","Enhance database AI instructions","database","instruction"),
    @("ENH-DB-TMPL-001","database/schema_template.md","Enhance schema template","database","template"),
    @("ENH-DB-TMPL-002","database/migration_template.md","Enhance migration template","database","template"),
    @("ENH-DB-GUIDE-001","database/performance_tuning.md","Enhance database performance guide","database","guide"),
    @("ENH-FE-INST-001","frontend/ai_instructions.md","Enhance frontend AI instructions","frontend","instruction"),
    @("ENH-FE-TMPL-001","frontend/page_template.md","Enhance page template","frontend","template"),
    @("ENH-FE-TMPL-002","frontend/component_template.md","Enhance component template","frontend","template"),
    @("ENH-FE-GUIDE-001","frontend/state_management.md","Enhance frontend state management guide","frontend","guide"),
    @("ENH-UI-INST-001","ui/ai_instructions.md","Enhance UI AI instructions","ui","instruction"),
    @("ENH-UI-GUIDE-001","ui/tokens.md","Enhance UI tokens guide","ui","guide"),
    @("ENH-UI-TMPL-001","ui/component_library_template.md","Enhance UI component library template","ui","template"),
    @("ENH-UI-GUIDE-002","ui/accessibility_rules.md","Enhance accessibility rules","ui","guide"),
    @("ENH-UX-INST-001","ux/ai_instructions.md","Enhance UX AI instructions","ux","instruction"),
    @("ENH-UX-TMPL-001","ux/user_journey_template.md","Enhance user journey template","ux","template"),
    @("ENH-UX-TMPL-002","ux/wizard_flow_template.md","Enhance wizard flow template","ux","template"),
    @("ENH-UX-GUIDE-001","ux/microcopy_guide.md","Enhance microcopy guide","ux","guide"),
    @("ENH-INT-INST-001","integration/ai_instructions.md","Enhance integration AI instructions","integration","instruction"),
    @("ENH-INT-TMPL-001","integration/api_client_template.md","Enhance API client template","integration","template"),
    @("ENH-INT-GUIDE-001","integration/webhook_handler.md","Enhance webhook handler guide","integration","guide"),
    @("ENH-INT-GUIDE-002","integration/auth_protocols.md","Enhance auth protocols guide","integration","guide"),
    @("ENH-QA-INST-001","qa/ai_instructions.md","Enhance QA AI instructions","qa","instruction"),
    @("ENH-QA-TMPL-001","qa/unit_test_template.md","Enhance unit test template","qa","template"),
    @("ENH-QA-TMPL-002","qa/ab_test_template.md","Enhance AB test template","qa","template"),
    @("ENH-QA-GUIDE-001","qa-and-checks/checklist.md","Enhance QA checklists","qa","guide"),
    @("ENH-DOC-GUIDE-001","docs/arch_diagrams.md","Enhance architecture diagram guide","docs","guide"),
    @("ENH-DOC-GUIDE-002","docs/prd_template.md","Enhance PRD template","docs","template"),
    @("ENH-SCRIPT-GUIDE-001","scripts/ci-cd-pipeline.md","Enhance CI/CD pipeline guide","scripts","guide"),
    @("ENH-SCRIPT-GUIDE-002","scripts/linting-rules.md","Enhance linting rules guide","scripts","guide")
)

foreach ($target in $targets) {
    Add-Enhancement $target[0] $target[1] $target[2] $sources $target[3] $target[4]
}

$failures = @()
foreach ($target in $targets) {
    $path = Join-Path $Root $target[1]
    if (-not (Test-Path $path)) {
        $failures += "$($target[1]) missing"
        continue
    }
    $raw = Get-Content $path -Raw
    if ($raw -notmatch [regex]::Escape($Marker)) { $failures += "$($target[1]) missing enhancement marker" }
    if ($target[1] -match 'ai_instructions\.md|template\.md|_template\.md|prd_template\.md') {
        if ($raw.Length -lt 2000) { $failures += "$($target[1]) under 2000 chars" }
        if ($raw -notmatch 'Analyzing all repository sources') { $failures += "$($target[1]) missing analysis sentence" }
        if ($raw -notmatch 'React') { $failures += "$($target[1]) missing React interface reference" }
        if ($raw -notmatch 'json') { $failures += "$($target[1]) missing JSON schema/interface reference" }
    }
}

if ($failures.Count -gt 0) {
    Write-TaskLog "ENH-VERIFY-001" "Recursive enhancement verification failed: $($failures -join '; ')" $sources "AI_PROMPTING_FOLDERSTRUCTURE" "PENDING"
    throw ($failures -join "`n")
}

Write-TaskLog "ENH-VERIFY-001" "Recursive enhancement verification passed without content regression" $sources "AI_PROMPTING_FOLDERSTRUCTURE" "DONE"
Write-Output "Recursive non-regression enhancement pass complete."

