import levelsData from '../data/levels.json';

/** A level as stored in levels.json (generated by scripts/generate-levels.mjs). */
export interface RawLevel {
  id: number;
  base: string;
  letters: string; // scrambled tile letters, uppercase
  mainWords: string[]; // grid words, uppercase
  bonusWords: string[]; // extra valid words, uppercase
}

export const LEVELS = levelsData as unknown as RawLevel[];
export const LEVEL_COUNT = LEVELS.length;

/** Levels are 1-indexed in the UI; data is 0-indexed. Clamps to a valid level. */
export function getLevel(levelNumber: number): RawLevel {
  const idx = Math.min(Math.max(levelNumber, 1), LEVEL_COUNT) - 1;
  return LEVELS[idx];
}

export const hasNextLevel = (levelNumber: number) => levelNumber < LEVEL_COUNT;

// ---- economy --------------------------------------------------------------

/** Coins earned for finding a main (grid) word: 5 + length·2. */
export const mainWordReward = (word: string) => 5 + word.length * 2;

/** Coins earned for finding a bonus (off-grid) word. */
export const BONUS_WORD_REWARD = 3;

/** Bonus words collected before the jar pays out. */
export const BONUS_JAR_SIZE = 5;
/** Coins awarded when the bonus jar fills. */
export const BONUS_JAR_REWARD = 25;

/** Reveal-a-letter hint price grows within a level: 10 + 5·(hints already used). */
export const revealLetterCost = (hintsUsedThisLevel: number) => 10 + 5 * hintsUsedThisLevel;
/** Reveal-an-entire-word hint price. */
export const REVEAL_WORD_COST = 75;

/** Coins for completing a level, scaled by star rating. */
export const levelCompleteReward = (stars: number) => 20 + stars * 15;

/** Star rating for a level based on how many hints were used. */
export function starsForHints(hintsUsed: number): number {
  if (hintsUsed === 0) return 3;
  if (hintsUsed <= 2) return 2;
  return 1;
}
